### PR TITLE
fix author label with more than 6 author initials

### PR DESCRIPTION
**Pull request by nglaeser**
The [CryptoBib manual](https://cryptobib.di.ens.fr/manual#author-labels) states that the author label rule is

> **Papers with four or more authors** ==> First letter of each author's last name *(up to 6)*

(italics mine). This PR fixes 3 entries I found for 2 papers total whose labels didn't follow this rule:

- `PoPETS:MSHLHSHHMNC18` -> `PoPETS:MSHLHS18`
- `SP:CHIKMRsVW21` -> `SP:CHIKMR21`
- `EPRINT:CHIKMRsVW20` -> `EPRINT:CHIKMR20`

### CODE REVIEW

**Comment by nglaeser** [comment]
@michelabdalla This PR has been open for a while, is there an issue I need to fix in order for it to be merged?

**Comment by michelabdalla** [comment]
Hi @nglaeser, there are currently some other inconsistencies related to the labeling rule for papers with more than 6 authors and we are trying to figure out the best way to address it without causing problems.

FYI, @fabrice102 ran a test in late July and found out the following:
  22  papers with >6 authors have <6 initials in key
 821 papers with >6 authors have =6 initials in key
1389 papers with >6 authors have >6 initials in key

**Comment by ludopulles** [comment]
I found some more quirks apart from what that 6 author format script gave, like:
- [EC:Burmester90a] should be [EC:BurDes90],
- [EPRINT:UnrDom12] should be [EPRINT:Unr12], giving two entries the same key, so there should actually be [EPRINT:Unr12a] and [EPRINT:Unr12b].

See https://github.com/ludopulles/cryptobib_tools/blob/master/format_entry.py for the script to fix those, it might need the modified lib in https://github.com/ludopulles/cryptobib_lib to succesfully output the bibtex file.

My plan is to make a pull request for https://github.com/ludopulles/crypto_db/tree/fix-252 to address the issue raised here, when/if #260 is merged.

**Comment by nglaeser** [comment]
@michelabdalla I see, thank you for the response!

**Pull request closed without merging**
